name: traefik

services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/shared/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./configs/shared/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./docker-volumes/traefik/cert.pem:/etc/traefik/certs/cert.pem:ro
      - ./docker-volumes/traefik/key.pem:/etc/traefik/certs/key.pem:ro
    networks:
      - traefik

  frontpage:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./configs/shared/demo-frontpage:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontpage.rule=Host(`localhost`)"
      - "traefik.http.routers.frontpage.tls=true"
      - "traefik.http.services.frontpage.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
